name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: energex
          MYSQL_USER: app
          MYSQL_PASSWORD: app
        ports: ["3306:3306"]
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uapp -papp"
          --health-interval=5s --health-timeout=5s --health-retries=10
      redis:
        image: redis:7
        ports: ["6379:6379"]

    steps:
      - uses: actions/checkout@v4

      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with: { php-version: "8.2" }
      - run: cd lumen-api && composer install --no-interaction --prefer-dist
      - run: |
          cd lumen-api
          php -r "file_put_contents('.env', 'APP_TIMEZONE=UTC\nDB_HOST=127.0.0.1\nDB_PORT=3306\nDB_DATABASE=energex\nDB_USERNAME=app\nDB_PASSWORD=app\nREDIS_HOST=127.0.0.1\nREDIS_PORT=6379\nJWT_SECRET=change_me\n');"
          php artisan migrate --force || true
          ./vendor/bin/phpunit

      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: cd node-cache && npm ci && npm test
