services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: energex
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  lumen-api:
    build: ./lumen-api
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  frontend:
    build: ./frontend
    depends_on:
      - lumen-api
    ports:
      - "5173:80"
    environment:
      - VITE_API_BASE=http://lumen-api:8000

volumes:
  mysql_data:
