services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: energex
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "app", "-papp"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  lumen-api:
    build: ./lumen-api
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: energex
      DB_USERNAME: app
      DB_PASSWORD: app
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: change_me
      JWT_TTL: 3600
      APP_TIMEZONE: UTC

  node-cache:
    build: ./node-cache
    ports:
      - "4000:4000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      PORT: 4000
      CORS_ORIGIN: http://localhost:5173
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: energex
      CACHE_TTL: 120

  frontend:
    build:
      context: ./frontend
    depends_on:
      - lumen-api
    ports:
      - "5173:80"
    environment:
      - VITE_API_BASE=http://localhost:8000

volumes:
  mysql_data:
